import React, { useEffect, useRef, useState } from 'react';

const IMG={
 clubHero:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=2000&q=85',
 clubSpace:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=85',
 clubStrength:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=85',
 clubReception:'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1200&q=85',
 clubLounge:'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=85',
 trainHero:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=2000&q=85',
 trainEnv:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=85',
 trainCoach:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1600&q=85',
 wellnessHero:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=2000&q=85',
 wellnessCalm:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1600&q=85',
 wellnessSpace:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=85',
 memberHero:'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=2000&q=85',
 memberLife:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=85',
 coachHero:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=2000&q=85',
 coachDetail:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1600&q=85',
 trialHero:'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&w=2000&q=85'
};
const nav=[['The Club','/club'],['Training','/training'],['Wellness','/wellness'],['Membership','/membership'],['Coaching','/coaching']];
export function Logo(){return <a className="logo" href="/" aria-label="ALTA home">ALTA<span className="logo-mark">/</span></a>}
export function Header(){const [open,setOpen]=useState(false),ref=useRef(null);useEffect(()=>{const f=e=>e.key==='Escape'&&open&&(setOpen(false),ref.current?.focus());window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[open]);return <header className="site-header"><div className="container header-inner"><Logo/><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([l,h])=><a href={h} key={l}>{l}</a>)}</nav><a className="button button--header" href="/trial">Book a free trial</a><button ref={ref} className="menu-button" type="button" aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}><span className="sr-only">{open?'Close menu':'Open menu'}</span><span className="menu-lines"><i/><i/></span></button></div><div id="mobile-navigation" className={`mobile-nav ${open?'is-open':''}`}><nav aria-label="Mobile navigation">{nav.map(([l,h])=><a href={h} key={l} onClick={()=>setOpen(false)}>{l}</a>)}<a className="button button--light" href="/trial" onClick={()=>setOpen(false)}>Book a free trial</a></nav></div></header>}
export function Footer(){return <footer className="site-footer"><div className="container footer-main"><div><a className="footer-logo" href="/">ALTA<span>/</span></a><p>Premium Fitness &amp; Wellness Club<br/>Lagos, Nigeria</p></div><div className="footer-links"><div><span className="footer-label">Explore</span>{nav.map(([l,h])=><a href={h} key={l}>{l}</a>)}</div><div><span className="footer-label">Contact</span><a href="mailto:hello@alta.club">Email</a><a href="/trial">WhatsApp</a><a href="/trial">Instagram</a></div><div><span className="footer-label">Legal</span><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ALTA</span><span>Train. Recover. Live.</span></div></footer>}
function Img({src,alt,variant='landscape',className=''}){return <div className={`image-frame image-frame--${variant} ${className}`}><img src={src} alt={alt} loading="lazy"/></div>}
function Btn({children,href='/trial',variant='primary'}){return <a className={`button button--${variant}`} href={href}>{children}</a>}
function Intro({eyebrow,title,children}){return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children&&<div className="section-intro__body">{children}</div>}</div>}
function PageHero({eyebrow,title,copy,image}){return <section className="support-hero"><Img src={image} alt="" variant="hero" className="support-hero__image"/><div className="support-hero__overlay"/><div className="container support-hero__content"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>}
function Gallery({items}){return <div className="support-gallery">{items.map((x,i)=><Img key={x[0]} src={x[1]} alt={x[0]} variant={i===0?'landscape':i===1?'portrait':'square'}/>)}</div>}
const disciplines=[['STRENGTH','Build foundational strength through structured resistance training.'],['CONDITIONING','Improve cardiovascular fitness and work capacity.'],['FUNCTIONAL TRAINING','Train movement, coordination and practical performance.'],['CARDIO','Build endurance through purposeful cardiovascular training.'],['SPORTS PERFORMANCE','Develop strength, speed and conditioning for athletic performance.']];
function Club(){return <><PageHero eyebrow="THE CLUB" title={<>DESIGNED TO<br/>MOVE YOU.</>} copy="A considered environment where training, recovery and everyday wellbeing come together." image={IMG.clubHero}/><main><section className="support-light"><div className="container editorial"><div><span className="eyebrow">THE SPACE</span><h2>A BETTER PLACE TO TRAIN.</h2></div><div><p className="body-large">Thoughtful spatial design, premium equipment and comfortable areas create a club built around how people actually train and live.</p><p>From focused training floors to recovery and social spaces, every environment has a clear purpose.</p></div></div></section><section className="support-dark"><div className="container"><Intro eyebrow="THE FACILITIES" title="EVERYTHING IN ITS PLACE."/><Gallery items={[["Training floor",IMG.clubSpace],["Strength area",IMG.clubStrength],["Reception",IMG.clubReception],["Lounge",IMG.clubLounge]]}/><div className="facility-line">TRAINING FLOOR · STRENGTH AREA · CARDIO · FUNCTIONAL TRAINING · RECOVERY · LOCKER FACILITIES · LOUNGE · SAUNA</div></div></section><section className="support-warm"><div className="container editorial"><div><span className="eyebrow">THE EXPERIENCE</span><h2>TRAIN. RECOVER. RESET.</h2></div><p className="body-large">ALTA moves beyond the conventional gym by giving training, recovery and everyday wellbeing equal space within one considered club.</p></div></section><FinalCta title="COME SEE ALTA FOR YOURSELF." secondary="Contact ALTA"/></main></>}
function Training(){return <><PageHero eyebrow="TRAINING" title="TRAIN WITH PURPOSE." copy="Training designed around strength, movement, conditioning and long-term performance." image={IMG.trainHero}/><main><section className="support-light"><div className="container"><Intro eyebrow="TRAINING DISCIPLINES" title="BUILD CAPACITY. MOVE WELL."/><div className="discipline-list">{disciplines.map(([a,b],i)=><article key={a}><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></div></section><section className="support-dark"><div className="container split-support"><div><span className="eyebrow">PERSONAL TRAINING</span><h2>TRAIN WITH GUIDANCE.</h2><p className="body-large">Work with an ALTA coach for one-to-one guidance, structured sessions and a more focused approach to your training.</p><Btn href="/coaching" variant="light">Meet our coaches</Btn></div><Img src={IMG.trainCoach} alt="Coach guiding a training session" variant="portrait"/></div></section><section className="support-image"><div className="container"><Intro eyebrow="TRAINING ENVIRONMENT" title="ROOM TO MOVE."/><Img src={IMG.trainEnv} alt="Modern training environment" variant="landscape"/></div></section><FinalCta title="READY TO TRAIN DIFFERENTLY."/></main></>}
function Wellness(){const things=[['SAUNA','A dedicated space to slow down after effort.'],['MOBILITY','Make movement quality part of the routine.'],['RECOVERY','Create room between hard sessions.'],['RESTORATION','A calmer environment for switching off.']];return <><PageHero eyebrow="WELLNESS" title="RECOVERY IS PART OF THE TRAINING." copy="Performance is built through the balance between effort, recovery and everyday wellbeing." image={IMG.wellnessHero}/><main><section className="support-warm"><div className="container"><Intro eyebrow="RECOVER" title="MAKE SPACE TO RESTORE."/><div className="discipline-list wellness-items">{things.map(([a,b],i)=><article key={a}><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></div></section><section className="support-dark"><div className="container split-support"><div><span className="eyebrow">NUTRITION</span><h2>FUEL WHAT YOU'RE BUILDING.</h2><p className="body-large">Healthy habits support the work you put into training. ALTA's approach keeps nutrition practical, balanced and connected to everyday life.</p></div><Img src={IMG.wellnessCalm} alt="Calm wellness interior" variant="portrait"/></div></section><section className="support-light"><div className="container editorial"><div><span className="eyebrow">THE BALANCE</span><h2>PERFORMANCE NEEDS SPACE.</h2></div><p className="body-large">Training. Recovery. Nutrition. Movement. The goal is not to choose one—it is to build a routine where each supports the others.</p></div></section><FinalCta title="MAKE WELLNESS PART OF YOUR ROUTINE." secondary="Explore ALTA"/></main></>}
const tiers=[['ALTA ESSENTIAL','For consistent access to the club and core training facilities.'],['ALTA SIGNATURE','For a more complete training and wellness experience.'],['ALTA PRIVATE','For members seeking a more personalized experience.']];
function Membership(){return <><PageHero eyebrow="MEMBERSHIP" title="FIND YOUR LEVEL." copy="Choose the ALTA experience that fits the way you train, recover and live." image={IMG.memberHero}/><main><section className="support-dark"><div className="container"><Intro eyebrow="MEMBERSHIP OPTIONS" title="THREE WAYS INTO ALTA."/><div className="membership-grid support-membership">{tiers.map(([a,b],i)=><article className="membership-card" key={a}><span className="membership-card__index">0{i+1}</span><h3>{a}</h3><p>{b}</p><a href="/trial">Enquire about membership →</a></article>)}</div></div></section><section className="support-light"><div className="container comparison"><span className="eyebrow">WHICH IS RIGHT FOR YOU?</span><h2>START WITH HOW YOU WANT TO EXPERIENCE THE CLUB.</h2><div className="comparison-list"><p><strong>ESSENTIAL</strong> — consistent access and the club's core training environment.</p><p><strong>SIGNATURE</strong> — a more complete training and wellness experience.</p><p><strong>PRIVATE</strong> — a more personalized experience.</p></div></div></section><section className="support-warm"><div className="container split-support split-support--reverse"><Img src={IMG.memberLife} alt="Member in a premium training environment" variant="landscape"/><div><span className="eyebrow">TRY ALTA FIRST</span><h2>SEE THE CLUB BEFORE YOU JOIN.</h2><p className="body-large">Experience the environment, explore the facilities and discover how ALTA fits your routine.</p><Btn>Book a free trial</Btn></div></div></section><FinalCta title="YOUR NEXT LEVEL STARTS HERE."/></main></>}
function Coaching(){return <><PageHero eyebrow="COACHING" title={<>YOUR GOALS.<br/>YOUR PROGRAM.</>} copy="Personal guidance for people who want a more focused approach to training." image={IMG.coachHero}/><main><section className="support-light"><div className="container split-support"><div><span className="eyebrow">PERSONAL TRAINING</span><h2>ONE-TO-ONE, WITH INTENTION.</h2><p className="body-large">Coaching brings structure and guidance to each session, with attention to technique, goals, programming and progress.</p></div><Img src={IMG.coachDetail} alt="Trainer working with a member" variant="portrait"/></div></section><section className="support-dark"><div className="container"><Intro eyebrow="COACHING SPECIALTIES" title="THE RIGHT FOCUS FOR THE WORK."/><div className="discipline-list">{['STRENGTH & CONDITIONING','PERSONAL TRAINING','SPORTS PERFORMANCE','MOVEMENT & MOBILITY'].map((x,i)=><article key={x}><span>0{i+1}</span><div><h3>{x}</h3><p>Focused coaching built around purposeful training.</p></div></article>)}</div></div></section><section className="support-warm"><div className="container editorial"><div><span className="eyebrow">THE COACH</span><h2>COACHING THAT MEETS YOU WHERE YOU ARE.</h2></div><p className="body-large">Our coaching philosophy is centered on clear guidance, thoughtful programming and helping each member train with intention. Individual coach profiles will be introduced as the ALTA team is finalized.</p></div></section><FinalCta title="TRAIN WITH INTENTION."/></main></>}
function FinalCta({title,secondary='Explore the club'}){return <section className="support-final"><div className="container"><span className="eyebrow">ALTA · LAGOS</span><h2>{title}</h2><div><Btn variant="light">Book a free trial →</Btn><Btn href="/club" variant="secondary">{secondary}</Btn></div></div></section>}
export function Trial(){return <><PageHero eyebrow="START HERE" title="YOUR FIRST SESSION STARTS HERE." copy="Come experience ALTA for yourself." image={IMG.trialHero}/><main><section className="support-light"><div className="container trial-layout"><div><span className="eyebrow">BOOK A FREE TRIAL</span><h2>COME EXPERIENCE ALTA.</h2><p className="body-large">Tell us a little about yourself and when you'd like to visit. We'll use your details to follow up.</p><div className="trial-contact"><strong>ALTA</strong><span>Lagos, Nigeria</span><span>Email: to be added</span><span>Phone: to be added</span><span>WhatsApp: to be added</span></div><div className="hours"><div><span>MON–FRI</span><strong>6:00 AM — 10:00 PM</strong></div><div><span>SAT–SUN</span><strong>7:00 AM — 8:00 PM</strong></div></div></div><TrialForm/></div></section><section className="support-warm"><div className="container"><span className="eyebrow">FIND ALTA</span><h2>LAGOS, NIGERIA.</h2><div className="map-frame"><iframe title="Map showing Lagos, Nigeria" src="https://www.openstreetmap.org/export/embed.html?bbox=3.25%2C6.38%2C3.55%2C6.62&layer=mapnik&marker=6.5244%2C3.3792" loading="lazy"/></div></div></section></main></>}
function TrialForm(){return <form className="trial-form" onSubmit={e=>e.preventDefault()}><label>First Name *<input name="firstName" required/></label><label>Last Name *<input name="lastName" required/></label><label>Email *<input type="email" name="email" required/></label><label>Phone Number *<input type="tel" name="phone" required/></label><label>Preferred Training Interest<select name="interest"><option>Strength Training</option><option>Personal Training</option><option>Functional Training</option><option>Cardio</option><option>Wellness</option><option>Not Sure Yet</option></select></label><label>Preferred Visit Day<input type="date" name="visitDay"/></label><label className="full">Message<textarea name="message" rows="5"/></label><button className="button button--primary full" type="submit">Request a free trial</button></form>}
export const pages={club:Club,training:Training,wellness:Wellness,membership:Membership,coaching:Coaching,trial:Trial};
export function SupportingApp({page}){const Page=pages[page]||Club;return <div id="top"><Header/><Page/><Footer/></div>}
